- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/CreateEventPage.tsx
- src/domain/event/EditEventPage.tsx
- src/domain/event/eventDetailsButtons/EventDetailsButtons.tsx
- src/domain/event/utils.ts
- Show error page when trying to edit past event
- Hide edit event button when event is in the past
- Show error messages on edit event and create event pages
**[PT-232](https://helsinkisolutionoffice.atlassian.net/browse/PT-232):**
> Prevent editing past events add error toasts

- src/common/components/imageInput/ImageInput.tsx
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- Add image size description to image input
- Handle too big file size with error message
**[PT-409](https://helsinkisolutionoffice.atlassian.net/browse/PT-409):**
> PT-409 | Add image file size description to create event page

- src/domain/events/EventsPage.tsx
- src/domain/events/constants.ts
- src/domain/events/query.ts
- src/domain/events/utils.ts
- src/generated/graphql.tsx
- Have separate load more buttons in events page and different queries for each category
**[PT-475](https://helsinkisolutionoffice.atlassian.net/browse/PT-475):**
> PT-475 | Separate queries for different event categories

- src/domain/event/eventKeywords/eventKeywords.module.scss
Ticket: https://helsinkisolutionoffice.atlassian.net/browse/PT-631
Before:
After:
> Use flex-wrap to fix overflowing content

- .env.development
- src/common/components/datepicker/Datepicker.tsx
- src/common/components/textInput/InputWrapper.tsx
- src/domain/app/i18n/constants.ts
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/eventForm/ValidationSchema.ts
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts
- src/utils/dateUtils.ts
Allow current day to be valid event starting day. Also changed error message text.
**[PT-632](https://helsinkisolutionoffice.atlassian.net/browse/PT-632):** 
Few component tests added for testing yesterday date and current date
Note! gif recorded on first of december, so it is the current day in it.
> PT-632 fix: Event starting day cannot be the current day

- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/place/PlaceSelector.tsx
PT-672 PlaceSelector was not showing places with 0 events, but by adding showAllPlaces to usePlacesQuery hook's variables, they are now included.
**[PT-672](https://helsinkisolutionoffice.atlassian.net/browse/PT-672):** 
CreateEventPage.test.tsx updated.
Test queries
Graphql place query from Kultus - Result is 2 entries:
https://palvelutarjotin-api.test.kuva.hel.ninja/graphql#operationName=Places&query=query Places(%24dataSource%3A String%2C %24divisions%3A [String]%2C %24page%3A Int%2C %24pageSize%3A Int%2C %24showAllPlaces%3A Boolean%2C %24sort%3A String%2C %24text%3A String) { places(dataSource%3A %24dataSource%2C divisions%3A %24divisions%2C page%3A %24page%2C pageSize%3A %24pageSize%2C showAllPlaces%3A %24showAllPlaces%2C sort%3A %24sort%2C text%3A %24text) { meta { count next …
> Fixed the PlaceSelector query to include places without events.

- .dockerignore
- package.json
- src/domain/app/i18n/constants.ts
- src/domain/event/eventForm/ValidationSchema.ts
- src/domain/event/eventForm/__tests__/EventForm.test.tsx
- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts
- src/utils/CommonEventFormTests.ts
- src/utils/dateUtils.ts
- src/utils/testUtils.tsx
- tsconfig.json
Currently there is no validation for enrolment date. These are added:
- enrolment cannot start in the past
- enrolment cannot start after the event has started
Both validation checks the inputted hours too.
https://helsinkisolutionoffice.atlassian.net/browse/PT-633
Previously (no errors):
After:
- Enrolment cannot start in the past
- enrolment cannot start after the event has started
> Pt-633: Enrolment can't start after event start and not in the past

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/app/layout/__tests__/Container.test.tsx
- src/domain/event/EditEventPage.tsx
- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/event/__tests__/EditEventPage.test.tsx
- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
- src/domain/event/eventBasicInfo/__tests__/__snapshots__/EventBasicInfo.test.tsx.snap
- src/domain/event/eventForm/EventForm.tsx
- src/domain/event/query.ts
- src/domain/event/types.ts
- src/domain/event/utils.ts
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/generated/graphql.tsx
- src/utils/CommonEventFormTests.ts
PT-689 PT-766. API already supported mandatory additional information, but frontend didn't. The new checkbox is used to make description field mandatory when creating an enrolment from Teacher's UI.
NOTE: For some reason couple of tests are still failing!
Added the new checkbox here:
Teacher's UI implementation: https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/77
Main task: https://helsinkisolutionoffice.atlassian.net/browse/PT-689
> Added pEvents' mandatory additional information field and data.

- .eslintrc.json
- package.json
- yarn.lock
disallow .only tests on pre-commit hook + run eslint first to fail faster
> disallow .only tests on pre-commit hook + run eslint first to fail faster

- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/event/__tests__/EditEventPage.test.tsx
- src/domain/event/eventForm/EventForm.tsx
- src/domain/event/eventForm/eventForm.module.scss
- src/domain/occurrence/EditOccurrencePage.tsx
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/__tests__/EditOccurrencePage.test.tsx
- src/domain/occurrence/__tests__/OccurrenceDetailsPage.test.tsx
- src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx
- src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx
- src/domain/occurrence/query.ts
- src/generated/graphql.tsx
- src/utils/__tests__/sortFavorably.test.ts
- src/utils/mockDataUtils.ts
- src/utils/sortFavorably.ts
Removed language field from event form, since the event language is now auto populated by API (https://github.com/City-of-Helsinki/palvelutarjotin/pull/131). **This PR needs that API change in order to work properly!**
PT-877 Added new languages to occurrence language selection.
PT-829 PT-857  Event form's basic information (step 1) included an inLanguage field which is now removed, since it is automatically populated with occurrences languages.
> Removed language field from event form

- src/common/components/form/fields/MultiDropdownField.tsx
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/event/__tests__/EditEventPage.test.tsx
- src/domain/event/eventForm/EventForm.tsx
- src/domain/event/eventForm/ValidationSchema.ts
- src/domain/event/eventForm/__tests__/EventForm.test.tsx
- src/domain/occurrence/__tests__/OccurrenceDetailsPage.test.tsx
- src/test/apollo-mocks/keywordSetMocks.ts
- src/utils/mockDataUtils.ts
- tsconfig.json
- Update some helper texts in event form
- Make target groups, categories and activities required in event form
- Delete requirement from keywords
**[PT-896](https://helsinkisolutionoffice.atlassian.net/browse/PT-896):** 
**[PT-771](https://helsinkisolutionoffice.atlassian.net/browse/PT-772):** 
**[PT-412](https://helsinkisolutionoffice.atlassian.net/browse/PT-412):**
> PT-896, PT-771, PT-412 | Better helping texts and mandatory keywords

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/event/__tests__/EventDetailsPage.test.tsx
- src/domain/event/editEventButtons/__tests__/__snapshots__/EditEventButtons.test.tsx.snap
- src/domain/event/eventDetailsButtons/__test__/EventDetailsButtons.test.tsx
- src/domain/event/eventForm/EventForm.tsx
- src/domain/event/eventLanguageSelector/EventLanguageSelector.tsx
- src/domain/occurrence/__tests__/EditOccurrencePage.test.tsx
- src/domain/occurrence/__tests__/OccurrenceDetailsPage.test.tsx
- src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx
- src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupLanguageInfo.tsx
- src/domain/occurrence/occurrenceInfo/OccurrenceInfo.tsx
PT-908. Using only 1 common language translation instead of 3 different ones, which content is still the same. Helps maintaining the code and the translations.  Also added  a new component named OccurrenceGroupLanguageInfo, which is having the same behavior that the component in palvelutarjotin-ui repo.
> Use common language translations everywhere.

- src/domain/app/i18n/constants.ts
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/eventForm/__tests__/EventForm.test.tsx
- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/EditOccurrencePage.tsx
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx
- src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts
- src/domain/occurrence/types.ts
- src/utils/CommonEventFormTests.ts
PT-481 Occurrence's date is validated against pEvent.enrolmentStart and pEvent.enrolmentEndDays fields.
Submitted as a draft, since this branch is basing on PR #156. It's still a ready implementation.
It would be nice to get improvement suggestions for passing the 2 new pEvent variables to occurrence validation. Now they are passed via occurrence form model.
> Improved occurrence form's date field validation

- src/common/components/form/fields/PlaceSelectorField.tsx
- src/domain/event/EditEventPage.tsx
- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/event/__tests__/EditEventPage.test.tsx
- src/domain/event/constants.ts
- src/domain/event/eventForm/EventForm.tsx
- src/domain/event/eventForm/ValidationSchema.ts
- src/domain/event/eventForm/VirtualEventCheckboxField.tsx
- src/domain/event/eventForm/eventForm.module.scss
- src/domain/event/types.ts
- src/domain/event/utils.ts
- src/domain/place/PlaceSelector.tsx
- Add virtual event checkbox
**[PT-647](https://helsinkisolutionoffice.atlassian.net/browse/PT-647):**
> PT-647 | Add virtual event checkbox to event form

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/EventDetailsPage.tsx
- src/domain/event/__tests__/EventDetailsPage.test.tsx
- Add more instructions to delete event modal
**[PT-1019](https://helsinkisolutionoffice.atlassian.net/browse/PT-1019):**
> PT-1019 | Add more instructions to delete event modal

- .env.development
- src/clients/apiReportClient/apiReportClient.ts
- src/clients/apiReportClient/useReportClientQuery.ts
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/app/routes/constants.ts
- src/domain/event/EventSummaryPage.tsx
PT-1024 PT-1032. Added apiReportClient which is implemented with Axios. When the API does not return csv file, toast is thrown. Events' enrolments csv file can be downloaded when API does not require authentication.
> Added download events' enrolments button to event summary page.

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/EventSummaryPage.tsx
- src/domain/event/__tests__/EventSummaryPage.test.tsx
- src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx
- src/domain/occurrences/occurrencesTableReadOnly/OccurrencesTableSummary.tsx
- src/domain/occurrences/occurrencesTableReadOnly/__tests__/OccurrencesTableSummary.test.tsx
- src/domain/occurrences/occurrencesTableReadOnly/occurrencesTableSummary.module.scss
- src/utils/testUtils.tsx
- Add cancel action to occurrences table
- Show badge if occurrence is cancelled
**[PT-1026](https://helsinkisolutionoffice.atlassian.net/browse/PT-1026):**
> PT-1026 | Add cancel action to occurrences table in summary page

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/CreateEventPage.tsx
- src/domain/event/EditEventPage.tsx
- src/domain/event/EventSummaryPage.tsx
- src/domain/event/__tests__/EventSummaryPage.test.tsx
- src/domain/event/eventForm/EventForm.tsx
- src/domain/event/eventForm/useEventFormSubmitRequests.tsx
- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/OccurrencesFormHandleContext.tsx
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
- src/domain/occurrence/utils.ts
- src/test/CreateOccurrencePageTestUtils.ts
- Submit also occurrence form when using save button for enrolment info form
- Also submit occurrence form when navigating to publish page if occurrence form is valid and filled
- Disable submit button on main event form when clicked and requests are pending
**[PT-1047](https://helsinkisolutionoffice.atlassian.net/browse/PT-1047):**
> Submit occurrence form if needed when saving enrolment form data

- src/common/components/textEditor/TextEditor.tsx
- src/domain/event/__tests__/CreateEventPage.test.tsx
> fix(editor): strip pasted styles in event description editor

- src/domain/app/register/RegistrationPendingPage.module.scss
- src/domain/app/register/RegistrationPendingPage.tsx
In future, instead of using a hard coded (Finnish only) text and a contact information address-block, the content should be fetched from to-be-done headless CMS.
PT-1113.
> fix: hard coded a Finnish registration pending text instead of lorem ipsum.

- src/domain/app/apollo/apolloClient.ts
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/events/utils.ts
- Fix bug where event list would disappear after pagination query return error from server
**[PT-1131](https://helsinkisolutionoffice.atlassian.net/browse/PT-1131):**
> PT-1131 | fix pagination when server returns error

- src/domain/event/__tests__/EventSummaryPage.test.tsx
- src/domain/event/eventPublish/EventPublish.tsx
The unpublish event button has never been in use and it was an unimplemented feature in UI, so the button is now removed, so it would not haunt the users. 
NOTE: Unpublish feature is already implemented in the API. It was only missing from UI, but it was not clear whether it is really wanted or not, because it could make a hazzle.
PT-1148.
> fix(occurrence): removed the unpublish event button

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/event/EventSummaryPage.tsx
- src/domain/event/__tests__/EventDetailsPage.test.tsx
- src/domain/event/__tests__/EventSummaryPage.test.tsx
- src/domain/event/eventBasicInfo/EventBasicInfo.tsx
- src/domain/event/eventCard/EventCard.tsx
- src/domain/event/eventCard/__tests__/EventCard.test.tsx
- src/domain/event/utils.ts
- src/domain/events/EventsPage.tsx
- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/ValidationSchema.ts
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/constants.ts
- src/domain/occurrence/enrolmentInfoFormPart/EnrolmentInfoFormPart.tsx
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
- src/domain/occurrence/types.ts
- src/domain/occurrence/utils.ts
- src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx
- src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx
- src/domain/occurrences/occurrencesTable/__tests__/ActionsDropdown.test.tsx
- src/domain/occurrences/occurrencesTableReadOnly/OccurrencesTableSummary.tsx
- src/domain/occurrences/occurrencesTableReadOnly/__tests__/OccurrencesTableSummary.test.tsx
- src/test/CreateOccurrencePageTestUtils.ts
- src/test/EventPageTestUtil.ts
- src/utils/mockDataUtils.ts
The enrolment information is shown only If the event's enrolment type is internal. If the enrolments are done externally or the event is unenrollable, enrolment status info won't be rendered. In event card also shows the enrolment type.
PT-849 PT-1102.
> feat(enrolment-type): events enrolment info differs on different enrolment type

- .gitignore
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/events/EventsPage.tsx
- src/domain/events/__tests__/EventsPage.test.tsx
- src/domain/events/eventsPage.module.scss
- src/hooks/useProfilePlaces.ts
- Add ability to filter events by locations that are in the profile.
**[PT-1203](https://helsinkisolutionoffice.atlassian.net/browse/PT-1203):** 
`yarn test EventsPage`
> feat: filter events by profile places

- .gitignore
- .testcaferc.json
- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
- Hide min and max fields when event doesn't have internal enrolment
**[PT-1215](https://helsinkisolutionoffice.atlassian.net/browse/PT-1215):**
> fix: hide min and max fields when not internal enrolment + improve tests

- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
- src/domain/occurrence/occurrencesFormPart/ValidationSchema.ts
- Hide also seats input when not internal enrolments
**[PT-1215](https://helsinkisolutionoffice.atlassian.net/browse/PT-1215):**
> fix: hide also seats input when not internal enrolment

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/app/routes/LocaleRoutes.tsx
- src/domain/app/routes/constants.ts
- src/domain/event/EventSummaryPage.tsx
- src/domain/event/__tests__/EventSummaryPage.test.tsx
- src/domain/event/eventSummaryPage.module.scss
- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/EditOccurrencesPage.tsx
- src/domain/occurrence/editOccurrencesPage.module.scss
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
- src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx
- src/domain/occurrences/occurrencesTable/__tests__/ActionsDropdown.test.tsx
- src/domain/occurrences/occurrencesTableReadOnly/OccurrencesTableSummary.tsx
- src/domain/occurrences/occurrencesTableReadOnly/__tests__/OccurrencesTableSummary.test.tsx
- Add ability to edit occurrences after event has been published
- Add loading indicators to occurrence table when deleting / canceling occurrence
**[PT-1228](https://helsinkisolutionoffice.atlassian.net/browse/PT-1228):**
> PT-1228 | Add ability to edit occurrences (add/delete)

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
- src/domain/event/eventPreviewCard/__tests__/__snapshots__/EventPreviewCard.test.tsx.snap
- src/domain/place/UnitPlaceSelector.tsx
- src/domain/place/placeText/PlaceText.tsx
- src/domain/place/query.ts
- src/generated/graphql.tsx
- src/test/apollo-mocks/placeMocks.ts
- src/test/apollo-mocks/schoolsAndKindergartensListMock.ts
API returns all the units (1000+ pcs) all at once from schoolsAndKindergartens graphql query. The Enrolment form autosuggest field for unit selection should be able to filter the list of units with an input value.
PT-1298 PT-1313.
Same ticket in palvelutarjotin-ui: https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/173
----
The list of schools and kindergartens is from Servicemap API, but the selected place is queried from LinkedEvents places-API
with error:
> feat: unit place selector uses schoolsAndKindergartens query

- src/domain/place/UnitPlaceSelector.tsx
PT-1357 PT-1343
Same ting done in palvelutarjotin-ui: https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/182
> fix: unit id fields entries are filtered in lowercase format

- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx
- src/domain/occurrence/enrolmentInfoFormPart/EnrolmentInfoFormPart.tsx
- Update enrolment link label to also have email
**[PT-1321](https://helsinkisolutionoffice.atlassian.net/browse/PT-1321):**
> PT-1321 | Update enrolment link label to also have email

- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/EditOccurrencesPage.tsx
- src/domain/occurrence/ValidationSchema.ts
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
- src/domain/occurrence/occurrencesFormPart/ValidationSchema.ts
- Fix edit occurrence page form (refactor enrolmentStart prop to be Date instead of datetime string)
- Improve enrolment Start date validation to also use start time to determine if datetime is in the future
**[PT-1432](https://helsinkisolutionoffice.atlassian.net/browse/PT-1432):**
> PT-1432 | EditOccurrencePage form fix

- src/headless-cms/components/cmsPage.module.scss
Image from CMS was rendered too big (pushed sidebar too small) and was not aligned very well.
> Add img and figure styles to fix cms page with big image

- src/domain/event/__tests__/CreateEventPage.test.tsx
- src/domain/event/eventForm/ValidationSchema.ts
PT-1489 PT-1490. This branch is an alternative for #267 (where the price field number is formatted / normalized). This branch makes the field fully free text.
> chore: convert price field to a free text field

- src/domain/app/header/Header.tsx
- src/headless-cms/components/__tests__/__snapshots__/CmsPage.test.tsx.snap
Adds root page links as the first link in the dropdown so that the root page is more easily accessible.
**[PT-1496](https://helsinkisolutionoffice.atlassian.net/browse/PT-1496)**
> PT-1496 | Add root navigation item as the first link

- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/Header.test.tsx
- src/headless-cms/hooks.ts
PT-1474. The CMS menu items are not visible in the header when the user has not logged in yet.
However, they should appear after a successfull login is done
> feat: cms menu loading skipped when user is not logged in

- src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx
refs PT-1569 (the contact info details were incorrectly placed)
**[PT-1569](https://helsinkisolutionoffice.atlassian.net/browse/PT-1569)**
Set up palvelutarjotin, palvelutarjotin-admin, palvelutarjotin-ui and tunnistamo locally, created an event, enrolled in it and then looked up the enrolment details in the palvelutarjotin-admin UI.
[PT-1569]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1569 | fix: use correct contact infos in enrolment details

- README.md
- update tunnistamo related instructions
- update docker-compose related instructions
- remove unnecessary URL names where the URL and its name are the same,
now the URL name can not go out of sync with the URL
refs PT-1569 (ran into trouble following the README.md's instructions)
refs PT-1640 (bug related to "docker-compose up" failing)
`-`
**[PT-1569](https://helsinkisolutionoffice.atlassian.net/browse/PT-1569)** 
**[PT-1640](https://helsinkisolutionoffice.atlassian.net/browse/PT-1640)** 
[PT-1569]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PT-1640]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjo …
> PT-1569, PT-1640 | update and clean up README

- .prod/nginx.conf.template
- Dockerfile
- package.json
- src/domain/app/routes/constants.ts
PT-1698
Read the following environment variables that are set in the pipeline process and set them in the respond of the Nginx `/readiness` -probe:
- RELEASE
- APP_VERSION
- COMMITHASH
- BUILD_TIME
---- 
Note: same work in Kukkuu https://github.com/City-of-Helsinki/kukkuu-admin/pull/243
> ci: add version and release information in the (Nginx) readiness probe

- src/domain/enrolment/EditEnrolmentPage.tsx
- src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx
- src/domain/enrolment/enrolmentForm/ValidationSchema.ts
- src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx
PT-1706
The errenous section of the site:
1. When the "Muokkaa"  /edit button was clicked, the locale was added twice and the page was rendered as an empty grey page
Solution: Remove the explicit locale set from the link path.
2. When the "Muokkaa" /edit was clicked from the dropdown menu, the locale was not added twice, but another error which was related to the form data initialization was thrown
Solution: This was a special case and the error was always written in Finnish, when there were no audience limits set for a study group.
----
EDIT: There was also a 3rd error which was in the group size validation. There were some default limits which was a bad practise. Now, the min group size is set to 1 and maximum can be left undefined or it's calculated from the remaining space left. IT …
> Fix enrolment edit link and form data initialization

- Dockerfile
refs PT-1714 (this added REACT_APP_ORIGIN)
[PT-1714](https://helsinkisolutionoffice.atlassian.net/browse/PT-1714)
[PT-1714]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1714 | fix(docker): pass REACT_APP_ORIGIN as argument to Dockerfile

- .env
- Dockerfile
- src/domain/app/footer/footer.module.scss
- src/domain/app/header/header.module.scss
- src/styles/main.scss
- src/styles/variables.scss
Docker compose related:
- Fix running docker compose by copy-pasting .env.development into .env
because docker compose build args doesn't support any other files
except .env, env_file setting affects environment variables in docker
compose but it does not affect build args.
- So in order to support docker compose build args and environment
variables being the same they have to either be put them into .env
(no other file will suffice, only .env) or e.g. set them using a
script to the environment before running docker compose.
Production styles related:
- Fix production styles by marking all styles in header.module.scss
as !important and --footer-background in footer.module.scss as
!important.
- This is a workaround to make sure styles are applied even if CSS
order varies. Switching from …
> PT-1725 | fix: fix production styles & running docker compose

- .env
- .env.development
- src/domain/event/__tests__/EventDetailsPage.test.tsx
- src/domain/event/eventBasicInfo/__tests__/__snapshots__/EventBasicInfo.test.tsx.snap
- src/domain/event/eventPreviewCard/__tests__/__snapshots__/EventPreviewCard.test.tsx.snap
- src/utils/mockDataUtils.ts
refs PT-1725
[PT-1725](https://helsinkisolutionoffice.atlassian.net/browse/PT-1725)
[PT-1725]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1725 | fix: use correct Linked Events test URL in testing

- src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
- src/domain/place/UnitPlaceSelector.tsx
- src/domain/place/query.ts
- src/generated/graphql.tsx
- src/test/apollo-mocks/schoolsAndKindergartensListMock.ts
PT-1733 PT-1743.
The unit place selector now uses a schools and kindergaratens list query with search-filter-parameter, since the API has changed the data source and the service now supports using it. So instead of always loading everything to memory, the client now requests a new options everytime when the search input changes.
NOTE: Needs https://github.com/City-of-Helsinki/palvelutarjotin/pull/350 as a dependency.
> feat: unit place selector search filter parameter

- README.md
The backend part related to this change:
- https://github.com/City-of-Helsinki/palvelutarjotin/pull/352
refs PT-1748
[PT-1748](https://helsinkisolutionoffice.atlassian.net/browse/PT-1748)
https://github.com/City-of-Helsinki/palvelutarjotin/pull/352
https://dev.azure.com/City-of-Helsinki/kultus/_git/kultus-pipelines/pullrequest/8807
[PT-1748]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1748?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1748 | docs: remove CREATE_SUPERUSER variable from backend

- .env
- Dockerfile
- src/domain/app/AppConfig.ts
- src/domain/app/header/Header.tsx
- src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap
- src/domain/app/i18n/en.json
- src/domain/app/i18n/fi.json
- src/domain/app/i18n/sv.json
- src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
Adds Helsinki profile link to the user menu
NOTE: external link icon is placed on the left, so all the links look the same.
**[PT-1777](https://helsinkisolutionoffice.atlassian.net/browse/PT-1777):**
[PT-1777]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1777 | feat: helsinki profile header link

- src/domain/app/AppConfig.ts
remove trailing slash from AppConfig.origin so
`${AppConfig.origin}/callback` as redirect_uri works
also:
- remove unused functions from AppConfig for clarity
- add getEnvAsUrl convenience function to AppConfig & use it
- move get* functions to AppConfig's end
refs PT-1730
> PT-1730 | Fix login by removing trailing slash from AppConfig.origin

- .github/dependabot.yml
Remove inexistent kuva-frontend team from dependabot reviewers
[PT-1864](https://helsinkisolutionoffice.atlassian.net/browse/PT-1864)
https://github.com/orgs/City-of-Helsinki/teams/kuva-frontend does not exist,
https://github.com/orgs/City-of-Helsinki/teams/kuva-front does exist but is not up to date
[PT-1864]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PT-1864 | Remove inexistent kuva-frontend team from dependabot reviewers

- src/domain/app/footer/Footer.tsx
- src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap
- src/domain/app/footer/footer.module.scss
- src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
PT-1916
Sometimes the footer links does not fit in a single row, so they should be wrapped to the next line.
NOTE: Similar fix in [palvelutarjotin-ui](https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/393).
> fix: flex-wrap footer links when they do not fit in single row

- src/domain/occurrence/CreateOccurrencePage.tsx
- src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx
PT-1683.
Deleting occurrences from event creation page's occurrences table did not update the table. Instead the deleted occurrence still persisted in the table. No notification was shown.
The occurrences table got it's data from event query which was fetched in CreateOccurrencePage. That query was using network only as a fetchPolicy, but the update of the deletion was done by updating the cache. Because of that, the query never saw the deletion and the UI did not get updated.
> fix: occurrences deletion UI update on event creation page

- vite.config.ts
PT-1927.
The `process.env` is not used anywhere, (except in Playwright).
Fixes the warning in startup saying:
```
$ vite preview
The `define` option contains an object with "PATH" for "process.env"
key.
It looks like you may have passed the entire `process.env` object to
`define`,
which can unintentionally expose all environment variables.
This poses a security risk and is discouraged.
```
> fix: remove process.env from vite config define
