City-of-Helsinki/palvelutarjotin-admin

.env, .env.development, .env.development.local.example, .gitlab-ci.yml, README.md, src/common/components/autoSuggest/AutoSuggest.tsx, src/common/components/autoSuggest/accessibility.tsx, src/common/components/autoSuggest/autoSuggest.module.scss, src/common/components/autoSuggest/contants.ts, src/common/components/form/fields/KeywordSelectorField.tsx, src/common/components/form/fields/PlaceSelectorField.tsx, src/domain/app/apollo/apolloClient.ts, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/eventForm/EventForm.tsx, src/domain/keyword/KeywordSelector.tsx, src/domain/keyword/KeywordText.tsx, src/domain/keyword/query.ts, src/domain/place/PlaceSelector.tsx, src/domain/place/PlaceText.tsx, src/domain/place/placeInfo/PlaceInfo.tsx, src/domain/place/query.ts, src/generated/graphql.tsx, src/utils/getLocalizedString.ts
Description:
1. Support selecting multiple options on auto-suggest component
2. Integrate UI with Palvelutarjotin GraphQL api: https://palvelutarjotin-api.test.kuva.hel.ninja/graphql
3. Implement keyword selector component
Testing: 
Feature can be tested on http://localhost:3000/fi/events/create ("Event keywords" -field)
If you are testing locally set following environmental variable:
- REACT_APP_API_URI=https://palvelutarjotin-api.test.kuva.hel.ninja/graphql
- REACT_APP_OIDC_AUTHORITY=https://tunnistamo.test.kuva.hel.ninja
=> PT-147 | Keyword selector component

src/common/components/dropdownSelect/DropdownMultiselect.tsx, src/common/components/dropdownSelect/DropdownSelect.tsx
Refactor for DrodownMultiSelect
=> use onSelectItemChange to get rid of debounce workaround

src/common/components/form/fields/CheckboxField.tsx, src/common/components/form/formGroup.module.scss, src/constants.ts, src/domain/app/i18n/constants.ts, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/routes/LocaleRoutes.tsx, src/domain/app/routes/constants.ts, src/domain/event/constants.ts, src/domain/event/eventForm/EventForm.tsx, src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/constants.ts, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts, src/domain/occurrence/eventOccurrenceForm/eventOccurrenceForm.module.scss, src/domain/occurrence/occurrencePage.module.scss
Add event occurrence page and form
**[PT-203](https://helsinkisolutionoffice.atlassian.net/browse/PT-203)**
Date and time picker missing
=> PT-203 | Add event occurrence page and form

src/common/components/autoSuggest/AutoSuggest.tsx, src/common/components/autoSuggest/autoSuggest.module.scss, src/common/components/backButton/BackButton.stories.tsx, src/common/components/backButton/BackButton.tsx, src/common/components/backButton/backButton.module.scss, src/common/components/textTitle/TextTitle.stories.tsx, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/routes/AppRoutes.tsx, src/domain/app/routes/LocaleRoutes.tsx, src/domain/app/routes/constants.ts, src/domain/event/CreateEventPage.tsx, src/domain/event/EditEventPage.tsx, src/domain/event/EventDetailsPage.tsx, src/domain/event/editEventButtons/EditEventButtons.tsx, src/domain/event/editEventButtons/editEventButtons.module.scss, src/domain/event/eventBasicInfo/EventBasicInfo.tsx, src/domain/event/eventDetailsButtons/EventDetailsButtons.tsx, src/domain/event/eventDetailsButtons/eventDetailsButtons.module.scss, src/domain/event/eventForm/EventForm.tsx, src/domain/event/eventLanguageSelector/EventLanguageSelector.tsx, src/domain/event/eventLanguageSelector/eventLanguageSelector.module.scss, src/domain/event/mutation.ts, src/domain/event/query.ts, src/domain/event/utils.ts, src/domain/events/EventsPage.tsx, src/generated/graphql.tsx
1. Page to edit existing event
2. Support different language versions of the event
3. Show warning if there are unsaved changes on the form
=> PT-167, PT-168 | Edit event page

package.json, src/common/components/datepicker/Datepicker.tsx, src/common/components/datepicker/Day.tsx, src/common/components/datepicker/Month.tsx, src/common/components/datepicker/MonthNavButton.tsx, src/common/components/datepicker/contants.ts, src/common/components/datepicker/datepicker.module.scss, src/common/components/datepicker/datepickerContext.tsx, src/common/components/form/fields/DateInputField.tsx, src/domain/app/i18n/constants.ts, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts, src/domain/occurrence/eventOccurrenceForm/eventOccurrenceForm.module.scss, src/icons/IconCalendar.tsx, yarn.lock
- Implement Datepicker component
- Integrate Datepicker to event occurrence form
- Add validations for date and enrolment date
**[PT-201](https://helsinkisolutionoffice.atlassian.net/browse/PT-201):**
=> PT-203 | Feature/date picker component

src/common/components/form/fields/TimepickerField.tsx, src/common/components/timepicker/Timepicker.tsx, src/common/components/timepicker/__tests__/Timepicker.test.tsx, src/common/components/timepicker/timepicker.module.scss, src/common/components/timepicker/utils.ts, src/domain/app/i18n/constants.ts, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts, src/domain/occurrence/eventOccurrenceForm/eventOccurrenceForm.module.scss
- Implement Timepicker
- Integrate Timepicker to event occurrence form
=> PT-202 | Feature/timepicker component

src/common/components/autoSuggest/AutoSuggest.tsx, src/common/components/datepicker/Datepicker.tsx, src/common/components/form/formGroup.module.scss, src/common/components/timepicker/Timepicker.tsx, src/domain/app/App.tsx, src/domain/app/ScrollToTop.tsx, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/query.ts, src/domain/image/mutation.ts, src/domain/image/query.ts, src/domain/keyword/query.ts, src/domain/myProfile/query.ts, src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/EditOccurrencePage.tsx, src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts, src/domain/occurrence/eventOccurrenceForm/eventOccurrenceForm.module.scss, src/domain/occurrence/mutation.ts, src/domain/occurrence/occurrencePage.module.scss, src/domain/occurrence/query.ts, src/domain/occurrence/utils.ts, src/domain/occurrences/query.ts, src/domain/place/query.ts, src/generated/graphql.tsx, src/utils/scrollToTop.ts
1. Open existing occurrence by clicking occurrence table row 
2. Implement page to create new occurrence
3. Implement page to edit existing occurrence
4. Correctly reset value on DatePicker and TimePicker components
5. Scroll to the back top when pathname is changed
=> PT-215 | Create/edit occurrence page

src/common/components/form/fields/CheckboxField.tsx, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/EditOccurrencePage.tsx, src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts, src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx, src/domain/occurrence/query.ts, src/domain/occurrence/utils.ts, src/domain/occurrences/OccurrencesPage.tsx, src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx, src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx, src/domain/occurrences/types.ts, src/domain/place/__mocks__/place.json, src/domain/place/placeInfo/__tests__/PlaceInfo.test.tsx, src/generated/graphql.tsx
1. Save occurrence languages
2. Save amount of seats and show them on occurrence details page as well
3. Add and save new field, autoAcceptance
4. Get rid of PlaceInfo test warnings
=> Add missing fields to occurrence form and details page

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/errorPage/ErrorPage.module.scss, src/domain/errorPage/ErrorPage.tsx, src/domain/event/EditEventPage.tsx, src/domain/event/EventDetailsPage.tsx, src/domain/notFound/NotFoundPage.tsx, src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/EditOccurrencePage.tsx, src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrences/OccurrencesPage.tsx
Add ErrorPage component and use it in error situations
**[PT-214](https://helsinkisolutionoffice.atlassian.net/browse/PT-214):** 
**[PT-213](https://helsinkisolutionoffice.atlassian.net/browse/PT-213):**
=> Add error/not found pages

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EditEventPage.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/event/eventForm/VenueInfoFormPart.tsx, src/domain/event/eventForm/eventForm.module.scss, src/domain/event/eventLocation/EventLocation.tsx, src/domain/event/eventLocation/eventLocation.module.scss, src/domain/event/utils.ts
Add venue amenities to event form and details page
**[PT-263](https://helsinkisolutionoffice.atlassian.net/browse/PT-263):** 
Still needs work in occurrence pages + need to add icons in event details page
=> Add venue amenities to event form and details page

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/CreateEventPage.tsx, src/domain/event/EditEventPage.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/event/eventForm/eventForm.module.scss, src/domain/event/types.ts, src/domain/event/utils.ts, src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/EditOccurrencePage.tsx, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/types.ts, src/domain/occurrence/utils.ts, src/domain/venue/types.ts, src/domain/venue/utils.ts, src/domain/venue/venueDataFields/VenueDataFields.tsx, src/domain/venue/venueDataFields/venueDataFields.module.scss, src/domain/venue/venueInfo/VenueInfo.tsx
Support editing venue field also on occurrence page
PT-335
Can be tested on http://localhost:3000/fi/events/palvelutarjotin:afzs7zf34q/occurrences/T2NjdXJyZW5jZU5vZGU6Njk=/edit
=> PT-335 | Support editing venue on occurrence form

package.json, src/common/components/form/fields/TextInputField.tsx, src/common/components/imageInput/ImageInput.tsx, src/common/components/loadingSpinner/LoadingSpinner.tsx, src/domain/event/CreateEventPage.tsx, src/domain/event/EditEventPage.tsx, src/domain/event/__mocks__/addEventResponse.json, src/domain/event/__mocks__/eventResponse.json, src/domain/event/__mocks__/imageMutationResponse.json, src/domain/event/__mocks__/imageResponse.json, src/domain/event/__mocks__/keywordResponse.json, src/domain/event/__mocks__/keywordsResponse.json, src/domain/event/__mocks__/placeResponse.json, src/domain/event/__mocks__/placesResponse.json, src/domain/event/__mocks__/profileResponse.json, src/domain/event/__mocks__/updateEventResponse.json, src/domain/event/__mocks__/venueResponse.json, src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/event/utils.ts, src/domain/image/imagePreview/ImagePreview.tsx, src/setupTests.ts
=> PT-354: CreateEventPage tests

src/domain/event/utils.ts
getExistingVenuePayload function was used when creating data object for new venue
=> PT-378 Fix small error from create event code

src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/DeleteEnrolmentModal.tsx
Fix problem where occurrence group info wouldn't update when deleting single enrolment
**[PT-379](https://helsinkisolutionoffice.atlassian.net/browse/PT-379):**
=> PT-379 Fix cache problem with occurrence when deleting enrolment

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EditEventPage.tsx, src/domain/occurrences/OccurrencesPage.tsx, src/generated/graphql.tsx
Add draft field to edit event mutation
**[PT-379](https://helsinkisolutionoffice.atlassian.net/browse/PT-379):**
=> PT-379 Fix/edit event draft

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/occurrence/__mocks__/responses.ts, src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx, src/domain/occurrence/enrolmentTable/actionsDropdown/ActionsDropdown.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/ApproveEnrolmentModal.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/DeclineEnrolmentModal.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/DeleteEnrolmentModal.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/EnrolleesList.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/EnrolmentModal.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/enrolmentModals.module.scss, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx, src/domain/occurrence/query.ts, src/domain/occurrences/OccurrencesPage.tsx, src/domain/occurrences/mutation.ts, src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx, src/domain/occurrences/occurrencesTable/CancelOccurrenceModal.tsx, src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx, src/generated/graphql.tsx
- Cancel enrolment button to occurrences list dropdown
- Cancel enrolment modal
**[PT-388](https://helsinkisolutionoffice.atlassian.net/browse/PT-388):**
=> PT-388 | Cancel enrolment button

src/domain/event/EditEventPage.tsx, src/domain/event/__mocks__/eventResponse.json, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/query.ts, src/domain/occurrence/__mocks__/responses.ts, src/generated/graphql.tsx, src/utils/mockDataUtils.ts
- Added endTime to the mutation input when updating event
**[PT-437](https://helsinkisolutionoffice.atlassian.net/browse/PT-437):**
=> PT-437 | Add event end time when updating event

src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrence/__mocks__/responses.ts, src/domain/occurrence/query.ts, src/generated/graphql.tsx
- Show correct enrolment numbers in occurrence details page
**[PT-401](https://helsinkisolutionoffice.atlassian.net/browse/PT-401):**
=> PT-401 | Fix numbers shown in enrolments table

src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/event/eventForm/EventForm.tsx
- Add 1 as default value to neededOccurrences in create event form
**[PT-414](https://helsinkisolutionoffice.atlassian.net/browse/PT-414):**
=> PT-414 | Add 1 as default value of needed occurrences

src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/EditOccurrencePage.tsx, src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx
- Keep some values when submitting and creating new occurrence
**[PT-361](https://helsinkisolutionoffice.atlassian.net/browse/PT-361):**
=> PT-361 | Keep some values when submitting and creating new occurrence

src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx, src/domain/occurrence/enrolmentTable/actionsDropdown/ActionsDropdown.tsx
- Fix custom message bug when approving and declining
**[PT-460](https://helsinkisolutionoffice.atlassian.net/browse/PT-460):**
=> PT-460 | Fix custom message bug when approving and declining

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EventDetailsPage.tsx, src/domain/event/eventDetailsPage.module.scss, src/domain/event/utils.ts
Add future occurrences list to delete event modal
**[PT-217](https://helsinkisolutionoffice.atlassian.net/browse/PT-217):**
=> PT-217 | Add Future occurrences to delete event modal

src/common/components/autoSuggest/AutoSuggest.tsx, src/common/components/datepicker/Datepicker.tsx, src/common/components/form/fields/DateInputField.tsx, src/common/components/form/fields/KeywordSelectorField.tsx, src/common/components/form/fields/PlaceSelectorField.tsx, src/common/components/textInput/InputWrapper.tsx, src/common/components/textInput/inputWrapper.module.scss, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/eventForm/ContactPersonInfoPart.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/event/eventForm/ImageSelectedFormPart.tsx, src/domain/keyword/KeywordSelector.tsx, src/domain/occurrences/OccurrencesPage.tsx, src/domain/place/PlaceSelector.tsx
- "Aseta" -> "Aseta julkaisuajankohta"
- Mark required fields with *
**[PT-419](https://helsinkisolutionoffice.atlassian.net/browse/PT-419):** 
**[PT-474](https://helsinkisolutionoffice.atlassian.net/browse/PT-474):**
=> PT-419, PT-474, PT-470 | Fix/improvements

src/domain/occurrence/occurrenceInfo/OccurrenceInfo.tsx, src/domain/occurrences/OccurrencesPage.tsx, src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx, src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx
Prevent edit/delete occurrence when event has been published
**[PT-459](https://helsinkisolutionoffice.atlassian.net/browse/PT-459):**
=> PT-459 | Feature/occurrences after publish

package.json, src/domain/events/EventsPage.tsx, src/domain/events/__tests__/EventsPage.test.tsx, src/domain/occurrences/__tests__/OccurrencesPage.test.tsx
- Add husky hook for commit (tests)
- Fix tests
=> Add husky hook for commit (tests)

src/common/components/datepicker/Datepicker.tsx, src/common/components/datepicker/datepicker.module.scss
- Further improve calendar icon functionality
**[PT-402](https://helsinkisolutionoffice.atlassian.net/browse/PT-402):**
=> PT-402 | Calendar icon as toggle button

package.json, public/index.html, public/manifest.json, src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap, src/domain/app/header/__tests__/__snapshots__/MobileNavbar.test.tsx.snap, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, yarn.lock
- Kultus rebrand
**[PT-473](https://helsinkisolutionoffice.atlassian.net/browse/PT-473):**
=> Kultus rebrand

package.json, src/common/components/datepicker/__tests__/Datepicker.test.tsx, src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/domain/occurrence/__tests__/EditOccurrencePage.test.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/__tests__/DeclineEnrolmentModal.test.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/__tests__/DeleteEnrolmentModal.test.tsx, yarn.lock
Improve test performance by configuring defaultHidden to true.
[More info](https://testing-library.com/docs/dom-testing-library/api-queries#byrole)
=> Improve test performance

package.json
- Fix commit hook and improve it
=> Fix commit hook and improve it

src/common/components/autoSuggest/AutoSuggest.tsx, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/events/EventsPage.tsx, src/domain/occurrence/enrolmentTable/EnrolmentTable.tsx, src/domain/occurrence/enrolmentTable/enrolmentTable.module.scss, src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx
- Accessibility improvements
**[PT-510](https://helsinkisolutionoffice.atlassian.net/browse/PT-510):**
=> Accessibility improvements

src/domain/event/EditEventPage.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/event/eventForm/ValidationSchema.ts
- Use different validation for date when editing event
**[PT-408](https://helsinkisolutionoffice.atlassian.net/browse/PT-408):**
=> PT-408 | Fix event date validation when editing

package.json, src/domain/events/EventsPage.tsx
- Fix duplicate event issue by adding publicationStatus public to past events query
**[PT-528](https://helsinkisolutionoffice.atlassian.net/browse/PT-528):**
=> PT-528 | Fix/duplicate event

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EditEventPage.tsx, src/domain/event/__mocks__/eventResponse.json, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/eventDetailsButtons/EventDetailsButtons.tsx, src/domain/event/eventDetailsButtons/__mocks__/eventData.json, src/domain/event/eventDetailsButtons/__test__/EventDetailsButtons.test.tsx, src/domain/event/eventDetailsButtons/__test__/__snapshots__/EventDetailsButtons.test.tsx.snap, src/domain/event/utils.ts
- Prevent editing events that have been published
**[PT-530](https://helsinkisolutionoffice.atlassian.net/browse/PT-530):**
=> PT-530 | Prevent editing event that has been published

src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/domain/occurrence/eventOccurrenceForm/ValidationSchema.ts
- Remove requirement from min and max group sizes in create occurrence form
**[PT-531](https://helsinkisolutionoffice.atlassian.net/browse/PT-531):**
=> PT-531 | Remove min max group size requirements

src/common/components/table/Table.tsx, src/common/components/table/table.module.scss, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EventSummaryPage.tsx, src/domain/event/eventPreviewCard/EventPreviewCard.tsx, src/domain/occurrence/query.ts, src/domain/occurrences/enrolmentsBadge/EnrolmentsBadge.tsx, src/domain/occurrences/enrolmentsBadge/__tests__/EnrolmentsBadge.test.tsx, src/domain/occurrences/enrolmentsBadge/__tests__/__snapshots__/EnrolmentsBadge.test.tsx.snap, src/domain/occurrences/enrolmentsBadge/enrolmentsBadge.module.scss, src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx, src/domain/occurrences/occurrencesTable/occurrencesTable.module.scss, src/generated/graphql.tsx, src/utils/mockDataUtils.ts
- Add new enrolments badge to occurrences table
**[PT-572](https://helsinkisolutionoffice.atlassian.net/browse/PT-572):**
=> PT-572 | Add new enrolments badge to occurrences table

src/common/components/tableDropdown/TableDropdown.tsx, src/domain/app/header/userDropdown/__tests__/UserDropdown.test.tsx, src/domain/app/header/userDropdown/__tests__/__snapshots__/UserDropdown.test.tsx.snap, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/__tests__/EventPreviewPage.test.tsx, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/event/eventImage/EventImage.tsx, src/domain/occurrence/enrolmentTable/actionsDropdown/ActionsDropdown.tsx, src/domain/occurrence/enrolmentTable/actionsDropdown/__tests__/ActionsDropdown.test.tsx, src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx, src/domain/occurrences/occurrencesTable/__tests__/ActionsDropdown.test.tsx
- Add tests to UserDropdown
- Add tests to table dropdowns
- Add tests to EventSummaryPage and EventPreviewPage
=> Add more tests

pull_request_template.md
added pull request template according to these instructions: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository
The template is taken from best-practices repo: https://github.com/City-of-Helsinki/bestpractice/blob/master/.github/pull_request_template.md
=> pull request template added

src/domain/event/eventCard/eventCard.module.scss
=> PT-603: Keyboard focus improve

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EventSummaryPage.tsx, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/event/eventPublish/EventPublish.tsx, src/domain/event/eventPublish/eventPublish.module.scss, src/domain/event/eventSummaryPage.module.scss
=> PT-598: Publish event accessibility fix

.github/workflows/production.yml, src/domain/enrolment/EditEnrolmentPage.tsx, src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx, src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx, src/domain/enrolment/enrolmentForm/ValidationSchema.ts, src/domain/enrolment/query.ts, src/domain/enrolment/types.ts, src/domain/enrolment/utils.ts, src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx, src/domain/occurrence/enrolmentDetails/__tests__/EnrolmentDetails.test.tsx, src/domain/occurrence/enrolmentDetails/__tests__/__snapshots__/EnrolmentDetails.test.tsx.snap, src/domain/occurrences/occurrencesTable/CancelOccurrenceModal.tsx, src/domain/studyLevel/query.ts, src/domain/studyLevel/useStudyLevels.ts, src/domain/studyLevel/utils.ts, src/generated/graphql.tsx, src/utils/mockDataUtils.ts
PT-729 (PT-728) Multiple study levels can be chosen.
=> Added studyLevel API changes

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrence/enrolmentTable/EnrolmentTable.tsx, src/domain/occurrence/occurrenceGroupInfo/OccurrenceGroupInfo.tsx, src/domain/occurrences/enrolmentsBadge/EnrolmentsBadge.tsx, src/domain/occurrences/enrolmentsBadge/__tests__/EnrolmentsBadge.test.tsx, src/domain/occurrences/enrolmentsBadge/__tests__/__snapshots__/EnrolmentsBadge.test.tsx.snap, src/domain/occurrences/enrolmentsBadge/enrolmentsBadge.module.scss, src/domain/occurrences/occurrencesTable/OccurrencesTable.tsx, src/utils/mockDataUtils.ts
- Inidicate if occurrence is full (yello background and tooltip)
- Support new SeatType
**[PT-731](https://helsinkisolutionoffice.atlassian.net/browse/PT-731):**
=> PT-731 | Indicate if occurrence is full, also support new SeatType

src/domain/app/ScrollToTop.tsx, src/domain/app/__tests__/ScrollToTop.test.tsx, src/domain/app/header/Header.tsx, src/domain/app/header/__tests__/Header.test.tsx, src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap, src/domain/app/header/header.module.scss, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/PageLayout.tsx, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/styles/common.scss
- Added focus to top functionality on route change
- Added skip link
**[PT-718](https://helsinkisolutionoffice.atlassian.net/browse/PT-718):** 
**[PT-584](https://helsinkisolutionoffice.atlassian.net/browse/PT-584):**
=> PT-718, PT-584 | Focus to top and skip link

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json
PT-410. The new input placeholder texts are taken from Events as was wanted.
Specs are communicated here: https://helsinkisolutionoffice.atlassian.net/browse/PT-410.
=> Changed place fields' placeholder texts to same they are in Events project.

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/event/eventForm/EventForm.tsx
=> PT-764 | Change additional criteria field to Activities

src/domain/enrolment/utils.ts, src/domain/occurrence/__tests__/OccurrenceDetailsPage.test.tsx, src/domain/occurrence/enrolmentTable/EnrolmentTable.tsx, src/utils/mockDataUtils.ts
PT-782 Fixed approved count that was missed earlier.
=> Added adults to a count of approved people.

src/domain/enrolment/enrolmentStatusBadge/enrolmentStatusBadge.module.scss, src/domain/occurrence/enrolmentTable/actionsDropdown/actionsDropdown.module.scss
PT-812 Replaced CSS color tram-dark-50 with tram-dark
=> Fixed dark tram colors.

src/domain/app/i18n/en.json, src/domain/app/i18n/sv.json
PT-822 Translations were mixed and 1 was missing.
=> Added a missing translation for "One group fills the event" -checkbox.

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EventDetailsPage.tsx, src/domain/event/eventCategorisation/EventCategorisation.tsx, src/domain/event/eventCategorisation/__tests__/EventCategorisation.test.tsx, src/domain/event/eventCategorisation/__tests__/__snapshots__/EventCategorisation.test.tsx.snap, src/domain/event/eventCategorisation/eventCategorisation.module.scss, src/domain/event/query.ts, src/generated/graphql.tsx
- Add activites and categories to event details page
**[PT-619](https://helsinkisolutionoffice.atlassian.net/browse/PT-619):**
=> Add activities (additionalCriteria) and categories to event details

src/common/components/loadingSpinner/loadingSpinner.module.scss
**[PT-801](https://helsinkisolutionoffice.atlassian.net/browse/PT-801):**
=> PT-801 | Fix loading spinner acting funny

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/eventForm/EventForm.tsx
PT-804 Added a guidance text for additional information mandatority. 
PT-811 Added placeholder text for an additional information for payment field.
=> Some new help texts to event form.

.github/workflows/ci.yml, .github/workflows/production.yml, .github/workflows/review.yml, .github/workflows/staging.yml, package.json, src/domain/app/i18n/fi.json, yarn.lock
Use same workflows & github messages and alerts as in tapahtumat workflows
=> Use same workflows & github messages and alerts as in tapahtumat workflows

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/occurrence/eventOccurrenceForm/EventOccurrenceForm.tsx
=> Added a missing translation for occurrence section help text.

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/occurrence/enrolmentDetails/__tests__/__snapshots__/EnrolmentDetails.test.tsx.snap
PT-929 Added new missing (still sketchy) study level translations.
=> Added new study level translations.

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json
=> Added translations for secondary level students.

src/constants.ts, src/domain/app/footer/Footer.tsx, src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/app/footer/footer.module.scss, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
=> PT-1021: Adds link to teachers UI 

src/constants.ts
=> Footer links fix typo

src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/event/eventForm/useSelectableEventLanguages.tsx, src/test/EventPageTestUtil.ts
PT-981. Added new tests for the new wizard component. There are tests for the new language selector. Added a new useSelectableEventLanguages hook which simplifies the EventForm -component.
=> CreateEventPage tests for the new wizard

.prettierignore, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/PageLayout.tsx, src/domain/app/layout/__tests__/PageLayout.test.tsx, src/domain/myProfile/MyProfileWrapper.tsx, src/domain/myProfile/query.ts, src/generated/graphql.tsx, src/utils/mockDataUtils.ts
- Add notification for newly signed users
**[PT-1013](https://helsinkisolutionoffice.atlassian.net/browse/PT-1013):**
=> PT-1013 | Add instruction text for newly signed providers

src/constants.ts, src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap
=> PT-1021: Fix explicit fi link

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/EditEventPage.tsx, src/domain/event/EventDetailsPage.tsx, src/domain/event/EventSummaryPage.tsx, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/event/eventDetailsPage.module.scss, src/domain/event/eventForm/EventForm.tsx, src/test/EventPageTestUtil.ts
- Add possibility to edit event after publishing it
- Add edit event ubtton to event details
- Show edit evetn button is summary details after publishing
**[PT-1020](https://helsinkisolutionoffice.atlassian.net/browse/PT-1020):**
=> PT-1020 | Edit event after publish

src/domain/events/EventsPage.tsx, src/domain/events/__tests__/EventsPage.test.tsx
=> Changed EventCard component to use short description in front page.

src/domain/app/i18n/sv.json
=> Fixed some Swedish translations.

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/__tests__/PageLayout.test.tsx, src/domain/myProfile/MyProfilePage.tsx, src/domain/myProfile/__tests__/MyProfilePage.test.tsx, src/domain/myProfile/mutation.ts, src/domain/myProfile/myProfileForm/MyProfileForm.tsx, src/domain/myProfile/myProfileForm/ValidationSchema.ts, src/domain/myProfile/myProfileForm/myProfileForm.module.scss, src/domain/myProfile/query.ts, src/domain/myProfile/utils.ts, src/generated/graphql.tsx, src/test/EventPageTestUtil.ts, src/utils/mockDataUtils.ts
PT-1074 PT-1084. In the my profile form the user can now give an input to request a new organisation.
=> Added a new field for 3rd party organisation request and updated schema.

src/domain/app/layout/__tests__/PageLayout.test.tsx, src/domain/event/__tests__/CreateEventPage.test.tsx, src/domain/myProfile/CreateMyProfile.tsx, src/domain/myProfile/MyProfilePage.tsx, src/domain/myProfile/__tests__/CreateMyProfile.test.tsx, src/domain/myProfile/__tests__/MyProfilePage.test.tsx, src/domain/myProfile/myProfileForm/MyProfileForm.tsx, src/domain/myProfile/myProfileForm/ValidationSchema.ts, src/domain/myProfile/utils.ts, src/domain/organisations/query.ts, src/generated/graphql.tsx, src/utils/mockDataUtils.ts
PT-1074 PT-1088 Only organisations with a type provider are fetched in my profile view.
PT-1074 PT-1093 Removed organisations fields from My profile form when in edit profile view.
Create form 
Edit form
=> Filtering organisations in my profile view by type

src/domain/app/heroBackground/HeroBackground.tsx, src/domain/app/heroBackground/heroBackground.module.scss, src/domain/app/register/RegistrationPendingPage.module.scss, src/domain/app/register/RegistrationPendingPage.tsx, src/domain/myProfile/CreateMyProfile.tsx, src/domain/myProfile/MyProfilePage.tsx, src/domain/myProfile/myProfile.module.scss
- Add styling to profile pages
**[PT-1099](https://helsinkisolutionoffice.atlassian.net/browse/PT-1099):**
=> PT-1099 | Add styling to profile form pages

src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx, src/domain/occurrence/occurrencesFormPart/utils.ts
- Go to publish page submits form before navigating
**[PT-1047](https://helsinkisolutionoffice.atlassian.net/browse/PT-1047):**
=> PT-1047 | Save event when trying to go publish page without saving

src/domain/occurrences/query.ts, src/generated/graphql.tsx
PT-1050 PT-1106.
NOTE: This needs new API https://github.com/City-of-Helsinki/palvelutarjotin/pull/191
=> Updated occurrences query schema.

.husky/commit-msg, CHANGELOG.md, README.md, commitlint.config.js, package.json, yarn.lock
- Add standard version to project (+commitlint)
**[PT-1108](https://helsinkisolutionoffice.atlassian.net/browse/PT-1108):**
=> PT-1108 | Add standard version

src/common/components/modal/modal.module.scss, src/domain/event/EventDetailsPage.tsx, src/domain/event/__tests__/EventDetailsPage.test.tsx, src/domain/event/eventDetailsPage.module.scss
- Show dots in modal if more than 5 occurrences are in the future
**[PT-1133](https://helsinkisolutionoffice.atlassian.net/browse/PT-1133):**
=> PT-1133 | Fix delete event modal

src/domain/events/EventsPage.tsx, src/domain/events/__tests__/EventsPage.test.tsx, src/domain/events/utils.ts
Fix event pagination error and improve tests
**[PT-1131](https://helsinkisolutionoffice.atlassian.net/browse/PT-1131):**
=> PT-1131 | Fix event pagination error and improve tests

src/domain/app/__tests__/ScrollToTop.test.tsx, src/domain/app/header/__tests__/Header.test.tsx, src/domain/app/layout/__tests__/PageLayout.test.tsx, src/domain/app/routes/__tests__/AppRoutes.test.tsx, src/domain/auth/authenticate.ts, src/domain/events/__tests__/EventsPage.test.tsx, src/headless-cms/components/CmsPage.tsx, src/headless-cms/components/__tests__/CmsPage.test.tsx, src/headless-cms/components/__tests__/__snapshots__/CmsPage.test.tsx.snap, src/test/cmsMocks.ts, tsconfig.json
=> test: cms page using AppRoutes

src/domain/app/i18n/sv.json
=> fix: add missing sv translations

src/common/components/form/fields/UnitPlaceSelectorField.tsx, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/enrolment/EditEnrolmentPage.tsx, src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx, src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx, src/domain/enrolment/enrolmentForm/ValidationSchema.ts, src/domain/enrolment/enrolmentForm/enrolmentForm.module.scss, src/domain/enrolment/types.ts, src/domain/place/UnitPlaceSelector.tsx
PT-1296
Same thing in palvelutarjotin-ui: https://github.com/City-of-Helsinki/palvelutarjotin-ui/pull/171
=> feat: study group unit field and selector

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx
=> fix: better translation for unit field checkbox

src/domain/enrolment/enrolmentForm/ValidationSchema.ts
- Make phone number not required when editing enrolment
**[PT-1345](https://helsinkisolutionoffice.atlassian.net/browse/PT-1345):**
=> PT-1345 |  Make phone number not required when editing enrolment

src/domain/app/i18n/constants.ts, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/enrolment/EditEnrolmentPage.tsx, src/domain/enrolment/__tests__/EditEnrolmentPage.test.tsx, src/domain/enrolment/enrolmentForm/EnrolmentForm.tsx, src/domain/enrolment/enrolmentForm/ValidationSchema.ts, src/domain/enrolment/query.ts, src/domain/enrolment/types.ts, src/domain/enrolment/utils.ts, src/generated/graphql-cms.tsx, src/generated/graphql.tsx, src/utils/mockDataUtils.ts, src/utils/typescript.utils.ts
- Fix enrolment form validation to match with Teacher UI
- Take edited enrolment group size into account with remaining seat when validating group size
**[PT-1347](https://helsinkisolutionoffice.atlassian.net/browse/PT-1347):**
=> PT-1347 | Fix validation in edit enrolment page + add tests

.github/workflows/production.yml
=> build: enable headless cms pages in prod

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/event/constants.ts, src/domain/event/eventForm/OrderableEventCheckboxField.tsx, src/domain/occurrence/CreateOccurrencePage.tsx, src/domain/occurrence/EditOccurrencesPage.tsx, src/domain/occurrence/ValidationSchema.ts, src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/domain/occurrence/constants.ts, src/domain/occurrence/locationFormPart/LocationFormPart.tsx, src/domain/occurrence/occurrencePage.module.scss, src/domain/occurrence/occurrencesFormPart/OccurrencesFormPart.tsx, src/domain/occurrence/occurrencesFormPart/ValidationSchema.ts, src/domain/occurrence/occurrencesFormPart/utils.ts, src/domain/occurrence/types.ts, src/domain/occurrence/utils.ts
- Add is orderable checkbox
**[PT-1353](https://helsinkisolutionoffice.atlassian.net/browse/PT-1353):**
=> PT-1353 | Add is orderable to school checkbox

.github/workflows/production.yml, public/index.html, public/manifest.json, src/constants.ts, src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/app/header/__tests__/__snapshots__/Header.test.tsx.snap, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/__tests__/PageLayout.test.tsx, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/domain/app/register/RegistrationPendingPage.tsx, src/domain/event/__tests__/EventDetailsPage.test.tsx, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/headless-cms/components/__tests__/__snapshots__/CmsPage.test.tsx.snap
=> PT-14137 | Delete beta texts

src/domain/enrolment/EditEnrolmentPage.tsx, src/domain/errorPage/__tests__/ErrorPage.test.tsx, src/domain/event/EditEventPage.tsx, src/domain/event/EventDetailsPage.tsx, src/domain/event/EventSummaryPage.tsx, src/domain/event/__tests__/EditEventPage.test.tsx, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/event/eventDetailsButtons/EventDetailsButtons.tsx, src/domain/event/eventDetailsButtons/__test__/EventDetailsButtons.test.tsx, src/domain/event/eventForm/EventForm.tsx, src/domain/occurrence/OccurrenceDetailsPage.tsx, src/domain/occurrence/__tests__/OccurrenceDetailsPage.test.tsx, src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx, src/domain/occurrence/enrolmentTable/EnrolmentTable.tsx, src/domain/occurrence/enrolmentTable/actionsDropdown/ActionsDropdown.tsx, src/domain/occurrence/occurrenceInfo/OccurrenceInfo.tsx, src/domain/occurrences/occurrencesTable/ActionsDropdown.tsx, src/domain/occurrences/occurrencesTable/__tests__/ActionsDropdown.test.tsx, src/domain/occurrences/occurrencesTableReadOnly/OccurrencesTableSummary.tsx, src/hooks/useGoBack.ts, src/hooks/useHistory.ts, src/utils/addParamsToQueryString.ts, src/utils/deleteParamsFromQueryString.ts, src/utils/extractLatestReturnPath.ts, src/utils/useQueryStringWithReturnPath.ts
Fix back navigation to pages where it was inconsistent
**[PT-1344](https://helsinkisolutionoffice.atlassian.net/browse/PT-1344):** 
Test cases:
URL: http://localhost:3000/fi/events/palvelutarjotin:af65pzzypu/summary
Event summary -> Muokkaa perustietoja -> Takaisin
Event summary -> Kopioi uuteen pohjaan -> Takaisin
Event summary -> Muokkaa perustietoja -> Tallenna tiedot
Event summary -> Näytä tapahtuman tiedot -> Takaisin
Event summary -> Näytä tapahtuman tiedot -> Vaihda kieltä -> Takaisin 
Event summary -> Näytä tapahtuman tiedot -> Muokkaa tapahtumaa -> Takaisin 
Event summary -> Näytä tapahtuman tiedot -> Muokkaa tapahtumaa -> Tallenna tiedot
Event summary -> Tapahtuma-aika -> Takaisin
Event summary -> Tapahtuma-aika -> Näytä tapahtuman tiedot -> Takaisin
Event summary -> …
=> Fix back navigation to pages where it was inconsistent

src/domain/occurrences/occurrencesTableReadOnly/OccurrencesTableSummary.tsx
- When occurrence spans multiple days, show start and end date in date column.
**[PT-1430](https://helsinkisolutionoffice.atlassian.net/browse/PT-1430):**
=> PT-1430 | Fix multiday occurrence time in occurrences table

src/domain/place/PlaceText.tsx, src/domain/place/UnitPlaceSelector.tsx, src/domain/place/placeInfo/PlaceInfo.tsx
=> fix: prevent fetching the places without place id

src/domain/app/i18n/fi.json
=> fix: a typo in the placeholder text "Etsi helsinkiläistä toimipistettä"

src/domain/app/register/RegistrationPendingPage.tsx
Updated registration pending page text and contact info.
**[PT-1554](https://helsinkisolutionoffice.atlassian.net/browse/PT-1554): Update contact information**
=> feat: update registration pending page text and contact info

src/constants.ts, src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/app/layout/PageLayout.tsx, src/domain/myProfile/myProfileForm/MyProfileForm.tsx
Added link to the terms of service CMS page to the sign up form.
**[PT-1559](https://helsinkisolutionoffice.atlassian.net/browse/PT-1559): Add the terms of service checkbox and validation to the sign up form**
=> PT-1559: Sign up form terms of service link

src/constants.ts, src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/headless-cms/components/__tests__/__snapshots__/CmsPage.test.tsx.snap
**[PT-1596](https://helsinkisolutionoffice.atlassian.net/browse/PT-1596): Update privacy policy link on teachers UI**
=> Update privacy policy links

azure-pipelines-release.yml, azure-pipelines-review.yml, azure-pipelines-test.yml
**[DEVOPS-495](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495):** 
[DEVOPS-495]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Azure DevOps pipelines

.prod/nginx.conf, Dockerfile
Openshift write access for needed directories
**[DEVOPS-495](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495):** 
[DEVOPS-495]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Platta build and deployment

.github/workflows/devops_review_tunnistamo.yml
**[DEVOPS-495](https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495):** 
[DEVOPS-495]: https://helsinkisolutionoffice.atlassian.net/browse/DEVOPS-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: workflow for tunnistamo usage on review environments DEVOPS-495

Dockerfile
node12 is causing build issues, upgrade to node14
**[PT-1669](https://helsinkisolutionoffice.atlassian.net/browse/PT-1669)** 
[PT-1669]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> node14 upgrade PT-1669

.env.development, src/domain/enrolment/EditEnrolmentPage.tsx, src/domain/enrolment/utils.ts, src/domain/eventQueueEnrolment/mutation.ts, src/domain/eventQueueEnrolment/query.ts, src/domain/myProfile/__tests__/CreateMyProfile.test.tsx, src/domain/occurrence/__tests__/CreateOccurrencePage.test.tsx, src/domain/occurrence/enrolmentDetails/EnrolmentDetails.tsx, src/domain/occurrence/enrolmentTable/enrolmentModals/utils.ts, src/generated/graphql-cms.tsx, src/generated/graphql.tsx
PT-1651 PT-1662.
There are some new queries and mutations:
EnrolEventQueueMutation
UnenrolEventQueueMutation
EventQueueEnrolmentQuery
EventQueueEnrolmentsQuery
Some endpoints are removed:
enrolments
studyGroups
studyGroup
Also, the query endpoints restrictions are now improved.
=> Update the Graphql schemas for Event Queue Enrolments

Dockerfile
=> Use Node 20 in Dockerfile

src/domain/app/routes/AppRoutes.tsx, src/domain/app/routes/LocaleRoutes.tsx
PT-1710.
The CIMODE has broken after the last great upgrade.
After fix:
=> fix: cimode localization

src/domain/app/i18n/en.json, src/domain/app/i18n/fi.json, src/domain/app/i18n/sv.json, src/domain/events/search/PlaceSelector.tsx
=> feat: add helper text to the own places filter

src/styles/common.scss
=> header logo should use a pointer as a cursor

.env, .env.development, .env.development.local.example
PT-1714.
An alternative for https://github.com/City-of-Helsinki/palvelutarjotin-admin/pull/324
=> Alternative fix to update .env* files

.env, .env.development, .env.development.local.example
refs PT-1714
[PT-1714](https://helsinkisolutionoffice.atlassian.net/browse/PT-1714)
[PT-1714]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1714 | fix: update .env* files

src/domain/app/header/Header.tsx, src/hooks/useRHHCConfig.ts
refs PT-1725
refs PT-1725
[PT-1725](https://helsinkisolutionoffice.atlassian.net/browse/PT-1725)
- check out this branch locally
- Either without docker:
- nvm use 20 (i.e. use node 20) or otherwise make sure you're using node 20
- yarn
- yarn start
- Or with docker:
- docker compose up --build
- open http://localhost:3000/
- log in using github account or something else
- click on the menu links and change languages etc and see that the pages & URLs etc work similarly as in https://provider.kultus.fi/ i.e. the current production environment
[PT-1725]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1725 | Fix routing & showing of selected CMS page by fixing getRoutedInternalHref & getIsItemActive functions

package.json, src/domain/app/apollo/apolloClient.ts, yarn.lock
refs PT-1725
[PT-1725](https://helsinkisolutionoffice.atlassian.net/browse/PT-1725)
[PT-1725]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1725?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1725 | fix: fix image uploading by installing apollo-upload-client and using it

package.json, src/headless-cms/components/CmsPage.tsx, src/headless-cms/utils.ts
**[PT-1607](https://helsinkisolutionoffice.atlassian.net/browse/PT-1607):** 
[PT-1607]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1607?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1607 | fix: cms page title and lang meta tags

src/constants.ts, src/domain/app/footer/Footer.tsx
refs PT-1723
[PT-1723](https://helsinkisolutionoffice.atlassian.net/browse/PT-1723)
[PT-1723]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1723 | Remove footer fallback links

.env, azure-pipelines-review.yml, azure-pipelines-test.yml
done:
- replace "https://kultus.hkih.stage.geniem.io/" with
"https://kultus.app-staging.hkih.hion.dev/"
refs PT-1751
[PT-1751](https://helsinkisolutionoffice.atlassian.net/browse/PT-1751)
[PT-1751]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1751 | Use new CMS url https://kultus.app-staging.hkih.hion.dev/

README.md, src/domain/app/footer/__tests__/__snapshots__/Footer.test.tsx.snap, src/domain/app/layout/__tests__/__snapshots__/PageLayout.test.tsx.snap, src/domain/event/__tests__/EventDetailsPage.test.tsx, src/domain/event/__tests__/EventSummaryPage.test.tsx, src/domain/occurrence/__tests__/CreateOccurrencePageEnrolmentInfo.test.tsx, src/headless-cms/components/__tests__/__snapshots__/CmsPage.test.tsx.snap, src/test/apollo-mocks/footerMenuMock.ts
=> feat: change domain to hel.fi

src/headless-cms/components/__tests__/CmsPage.test.tsx
=> fix: cms page test

src/domain/app/i18n/sv.json
Note: translations from screenshots are not found, or fixed earlier
**[PT-1633](https://helsinkisolutionoffice.atlassian.net/browse/PT-1633):**
[PT-1633]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1633 | Suggested translations update

package.json, src/domain/app/__tests__/__snapshots__/apolloRHHC.test.tsx.snap, yarn.lock
Update HCRC version to alpha205 to have the same Header loading changes as in Kukku
**[PT-1794](https://helsinkisolutionoffice.atlassian.net/browse/PT-1794):**
[PT-1794]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1794 Header loading with new hcrc version

src/domain/app/header/Header.tsx
**[PT-1815](https://helsinkisolutionoffice.atlassian.net/browse/PT-1815):**
[PT-1815]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1815 | fix: mobile navigation

.env.development, src/domain/app/login/LoginPage.tsx, src/domain/auth/KultusAdminHDSLoginCallbackHandler.tsx
**[PT-1817](https://helsinkisolutionoffice.atlassian.net/browse/PT-1817)**
[PT-1817]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: login redirect

LICENSE
Add `LICENSE` file using MIT license
[PT-1877](https://helsinkisolutionoffice.atlassian.net/browse/PT-1877)
[PT-1877]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1877 | Add `LICENSE` file using MIT license

index.html
PT-1874 PT-1892.
Add CSP meta-tag to index.html. Copied from Kukkuu UI.
=> feat(CSP): add CSP meta tag

package.json, src/domain/app/__tests__/__snapshots__/apolloRHHC.test.tsx.snap, src/utils/time/format.ts, src/utils/time/utils.ts, yarn.lock
Upgrade `date-fns`, install `@date-fns/tz`and fix the timezone to date and time formatters
=> Upgrade `date-fns` and fix timezone to date and time formatters

package.json, yarn.lock
Fix dependabot issues:
- https://github.com/City-of-Helsinki/palvelutarjotin-admin/security/dependabot/136
- https://github.com/City-of-Helsinki/palvelutarjotin-admin/security/dependabot/125
by resolving @types/cookie, hds-react/cookie and hds-react/@babel/runtime
in package.json's resolutions.
And upgrade everything to latest minor.
[PT-1807](https://helsinkisolutionoffice.atlassian.net/browse/PT-1807)
[PT-1807]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1807 | Resolve @types/cookie, hds-react/cookie, hds-react/@babel/runtime

src/clients/apiReportClient/apiReportClient.ts, src/domain/app/apollo/apolloClient.ts, src/domain/occurrence/CreateOccurrencePage.tsx, src/headless-cms/__tests__/utils.test.ts, src/headless-cms/apollo/apolloClient.ts, src/headless-cms/utils.ts, src/test/filterConsole.ts, src/test/vitest-setup.ts
SonarCloud reliability related fixes & tests' console filtering.
Please **see commit messages** for details.
[PT-1911](https://helsinkisolutionoffice.atlassian.net/browse/PT-1911)
[PT-1911]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1911 | Reliability fixes

.husky/pre-commit, CHANGELOG.md, README.md, package.json, public/hds-favicon-kit/README.md, src/domain/auth/README.md, yarn.lock
=> chore: add doctoc to pre-commit hook

.dockerignore, .env.development.local.example, .env.example, README.md, docs/setup-tunnistamo.md
PT-1880.
Add more content to README. Use [Kukkuu UI](https://github.com/City-of-Helsinki/kukkuu-ui) as a base for content and style.
=> docs: improve readme

src/domain/app/App.tsx, src/domain/app/layout/__tests__/PageLayout.test.tsx, src/domain/organisation/contextProviders/useStoredOrganisationState.tsx, src/utils/testUtils.tsx
=> fix: always navigate to root after organisation select

.env.playwright.local.example, .github/workflows/playwright.yml, .gitignore, package.json, playwright.config.ts, src/playwright/README.md, src/playwright/constants.ts, src/playwright/pages/base.page.ts, src/playwright/pages/login.page.ts, src/playwright/routeInterceptors.ts, src/playwright/testWithFixtures.ts, src/playwright/tests/languageChange.spec.ts, src/playwright/types.ts, vite.config.ts, yarn.lock
**NOTE**: This is very similar to what was done in palvelutarjotin-ui very recently.
Test login page's language changing with Playwright.
Includes the basic setup i.e. README, configurations etc for Playwright.
[PT-1920](https://helsinkisolutionoffice.atlassian.net/browse/PT-1920)
[PT-1920]: https://helsinkisolutionoffice.atlassian.net/browse/PT-1920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PT-1920 | Test login page's language changing with Playwright
